// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCxBS9aKph0G54zs0su3YPPLY-4TeNR2Q',
    appId: '1:761546808711:web:ab130612c0a20a048b8722',
    messagingSenderId: '761546808711',
    projectId: 'travel-company-az',
    authDomain: 'travel-company-az.firebaseapp.com',
    databaseURL: 'https://travel-company-az-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-company-az.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1nQld0lFkKXQvRpnSpdpBC5orpI-FJKE',
    appId: '1:761546808711:android:cbf5d0f11fbff00e8b8722',
    messagingSenderId: '761546808711',
    projectId: 'travel-company-az',
    databaseURL: 'https://travel-company-az-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-company-az.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkoCh2VE3iCnqv17CQKdBB3xXfLdPjb8',
    appId: '1:761546808711:ios:bb9b3ee96481eee48b8722',
    messagingSenderId: '761546808711',
    projectId: 'travel-company-az',
    databaseURL: 'https://travel-company-az-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-company-az.appspot.com',
    iosBundleId: 'com.example.travelcompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDkoCh2VE3iCnqv17CQKdBB3xXfLdPjb8',
    appId: '1:761546808711:ios:bb9b3ee96481eee48b8722',
    messagingSenderId: '761546808711',
    projectId: 'travel-company-az',
    databaseURL: 'https://travel-company-az-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-company-az.appspot.com',
    iosBundleId: 'com.example.travelcompany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCxBS9aKph0G54zs0su3YPPLY-4TeNR2Q',
    appId: '1:761546808711:web:ce4342d9fb58efd88b8722',
    messagingSenderId: '761546808711',
    projectId: 'travel-company-az',
    authDomain: 'travel-company-az.firebaseapp.com',
    databaseURL: 'https://travel-company-az-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-company-az.appspot.com',
  );
}
